name: "Test env"
on:
  - workflow_dispatch
  - push

jobs:
  github:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      TEST_VAR: job env

    steps:
      - name: "Echo ENV"
        run : |
          echo "${{ vars.TEST_VAR }}"
          echo $TEST_VAR
          TEST_VAR="declare in pipeline"
          echo $TEST_VAR
          echo "${{ env.TEST_VAR }}"