name: "Test env"
on:
  - workflow_dispatch
  - push

jobs:
  github:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: "Echo ENV"
        run : |
          echo "${{ env.TEST_VAR }}"