name: "Test env"
on:
  - workflow_dispatch
  - push

jobs:
  github:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      TEST_VAR: job env
    permissions:
      contents: write
  
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "GitHub CLI Setup"
        uses: sersoft-gmbh/setup-gh-cli-action@v2
        with:
          version: stable
          github-token: ${{ secrets.GITHUB_TOKEN}}
      - name: "GitHub create Release"
        if: 0
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=1.0.0
          
          gh release create "${VERSION}" -t "${VERSION}" --generate-notes --verify-tag

      - name: "GitHub Release as Draft"
        if: 1
        run: |
          VERSION=1.0.0
          
          gh release edit "${VERSION}" --draft=false --prerelease=true