name: "Test env"
on:
  - workflow_dispatch
  - push

jobs:
  github:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      TEST_VAR: job env
    permissions:
      contents: write
  
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "GitHub CLI Setup"
        uses: sersoft-gmbh/setup-gh-cli-action@v2
        with:
          version: stable
          github-token: ${{ secrets.GITHUB_TOKEN}}
      - name: "GitHub create Release"
        run: |
          VERSION=1.0.0
          git config --global user.email hoangvanhung6876@gmail.com
          git config --global user.name hung
          git tag "${VERSION}"
          git push origin "${VERSION}"

          gh release create "${VERSION}" -t "${VERSION}" --generate-notes --verify-tag