name: Main workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      id: create_file
      uses: HV-Hung/workflow-create-file@main
    - name: Use file
      run: cat ${{ steps.reusable.outputs.secrets_file }}